project:
  type: website

website:
  title: "Venkat Ravi" 
  site-url: xyz
  description: "This is Venkat's personal Blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/rkvenkat
      - icon: twitter
        href: https://twitter.com/venkat_xyz
      - icon: linkedin
        href: https://www.linkedin.com/in/venkata-ravi/
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

